// Manual frontend types — types not generated by ts-rs
// Generated types live in $lib/bindings/

import type { ApiTag } from "$lib/bindings";
import type { ProjectStatus } from "$lib/bindings";
import type { JSONContent } from "@tiptap/core";

// Frontend alias
export type TagWithIcon = ApiTag;

// Request types (include `id` for client routing, not present in Rust request structs)
export interface CreateProjectData {
  name: string;
  slug?: string;
  shortDescription: string;
  description: string;
  status: ProjectStatus;
  githubRepo?: string;
  demoUrl?: string;
  tagIds: string[];
  detailContent?: JSONContent | null;
}

export interface UpdateProjectData extends CreateProjectData {
  id: string;
}

export interface CreateTagData {
  name: string;
  slug?: string;
  icon?: string;
  color?: string;
}

export interface UpdateTagData extends CreateTagData {
  id: string;
}

// Vestigial — auth is cookie-based, not token-based
export interface AuthSession {
  token: string;
  expiresAt: string;
}
