// Manual frontend types — types not generated by ts-rs
// Generated types live in $lib/bindings/

import type { ApiTag } from "$lib/bindings";
import type { ProjectStatus } from "$lib/bindings";

// Frontend alias
export type TagWithIcon = ApiTag;

// Request types (include `id` for client routing, not present in Rust request structs)
export interface CreateProjectData {
  name: string;
  slug?: string;
  shortDescription: string;
  description: string;
  status: ProjectStatus;
  githubRepo?: string;
  demoUrl?: string;
  tagIds: string[];
}

export interface UpdateProjectData extends CreateProjectData {
  id: string;
}

export interface CreateTagData {
  name: string;
  slug?: string;
  icon?: string;
  color?: string;
}

export interface UpdateTagData extends CreateTagData {
  id: string;
}

// Stubbed types (no backend implementation yet)
export type EventLevel = "info" | "warning" | "error";

export interface AdminEvent {
  id: string;
  timestamp: string;
  level: EventLevel;
  target: string;
  message: string;
  metadata?: Record<string, unknown>;
}

// Vestigial — auth is cookie-based, not token-based
export interface AuthSession {
  token: string;
  expiresAt: string;
}
