// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an insert or move lands, relative to the existing block list.
 */
export type Anchor = { "at": "start" } | { "at": "end" } | { "at": "after", id: string, } | { "at": "before", id: string, };
