// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventLevel } from "./EventLevel";

/**
 * API response type for events
 */
export type ApiEvent = { id: string, eventType: string, level: EventLevel, entityType: string | null, entityId: string | null, actor: string | null, message: string, metadata: Record<string, unknown> | null, createdAt: string, };
