// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiMediaVariant } from "./ApiMediaVariant";
import type { ApiVideoOriginal } from "./ApiVideoOriginal";

/**
 * API response for media variants
 */
export type ApiMediaVariants = { thumb?: ApiMediaVariant, medium?: ApiMediaVariant, full?: ApiMediaVariant, original?: ApiMediaVariant, poster?: ApiMediaVariant, video?: ApiVideoOriginal, };
