// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response for media variant with full URL
 */
export type ApiMediaVariant = { url: string, width: number, height: number, };
