// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiProjectLink } from "./ApiProjectLink";

export type ApiProject = {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  links: Array<ApiProjectLink>;
};
