// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiProjectLink } from "./ApiProjectLink";
import type { ApiProjectMedia } from "./ApiProjectMedia";
import type { ApiRelatedProject } from "./ApiRelatedProject";
import type { ApiTag } from "./ApiTag";
import type { ProjectStatus } from "./ProjectStatus";
import type { TerminalCast } from "./TerminalCast";

/**
 * Single-project response that additionally carries the rich detail content.
 *
 * Returned only by the single-project endpoint (`GET /api/projects/{ref}`) —
 * never in list responses, so the homepage payload stays free of every
 * project's full `ProseMirror` JSON. Feeds both the admin editor and the public
 * `/projects/{slug}` page.
 */
export type ApiProjectDetail = { 
/**
 * When an authored/editorial field last changed (RFC 3339). Surfaced so the
 * admin authoring UI can show a "last edited" signal; background
 * GitHub-activity syncs do not affect it.
 */
updatedAt: string, 
/**
 * `ProseMirror`/`TipTap` document JSON, or null when the project has no detail page.
 */
detailContent?: unknown, 
/**
 * Authored CLI-hero transcript; absent for non-CLI projects.
 */
terminalCast?: TerminalCast, 
/**
 * Curated related projects in authored order (resolved server-side from the
 * `project_relations` table). Empty when none are authored.
 */
related: Array<ApiRelatedProject>, tags: Array<ApiTag>, media: Array<ApiProjectMedia>, status: ProjectStatus, description: string, githubRepo?: string, demoUrl?: string, createdAt: string, lastActivity: string, 
/**
 * Authored primary label; the rail's "Type" slot (replaces "Language").
 */
projectType?: string, 
/**
 * When true the page hides repo links and shows the closed-source callout.
 */
sourceClosed: boolean, 
/**
 * Explicit accent hex; frontend falls back to `#71717a` when absent.
 */
accentColor?: string, id: string, slug: string, name: string, shortDescription: string, links: Array<ApiProjectLink>, };
