// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiProjectLink } from "./ApiProjectLink";
import type { ApiProjectMedia } from "./ApiProjectMedia";
import type { ApiTag } from "./ApiTag";
import type { ProjectStatus } from "./ProjectStatus";

/**
 * Single-project response that additionally carries the rich detail content.
 *
 * Returned only by the single-project endpoint (`GET /api/projects/{ref}`) —
 * never in list responses, so the homepage payload stays free of every
 * project's full `ProseMirror` JSON. Feeds both the admin editor and the public
 * `/projects/{slug}` page.
 */
export type ApiProjectDetail = { 
/**
 * `ProseMirror`/`TipTap` document JSON, or null when the project has no detail page.
 */
detailContent?: unknown, tags: Array<ApiTag>, media: Array<ApiProjectMedia>, status: ProjectStatus, description: string, githubRepo?: string, demoUrl?: string, createdAt: string, lastActivity: string, id: string, slug: string, name: string, shortDescription: string, links: Array<ApiProjectLink>, 
/**
 * Whether this project has rich detail content (a `/projects/{slug}` page).
 * Lets cards link internally without shipping the full content JSON in lists.
 */
hasDetail: boolean, };
