// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiSiteIdentity } from "./ApiSiteIdentity";
import type { ApiSocialLink } from "./ApiSocialLink";

export type ApiSiteSettings = {
  identity: ApiSiteIdentity;
  socialLinks: Array<ApiSocialLink>;
};
