// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiSocialLink = { id: string, platform: string, label: string, value: string, icon: string, visible: boolean, displayOrder: number, };
