// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiTagWithCount = {
  projectCount: number;
  id: string;
  slug: string;
  name: string;
  icon?: string;
  color?: string;
};
