// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response for video original
 */
export type ApiVideoOriginal = { url: string, mime: string, duration?: number, };
