// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One content block. `data` carries the type-specific payload (e.g. a prose
 * block's markdown) and is never interpreted here.
 */
export type Block = { id: string, type: string, data: unknown, };
