// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A new block's content for `insert`. The store owns the `id`, so it isn't
 * part of the input; `type` is required.
 */
export type BlockInput = { type: string, data: unknown, };
