// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `set` payload. `data` always replaces the block's data; `type` is optional
 * — omit it to change data while keeping the block's existing type, or supply
 * it to retype the block in place.
 */
export type BlockPatch = { type?: string, data: unknown, };
