// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { BlockInput } from "./BlockInput";
import type { BlockPatch } from "./BlockPatch";

/**
 * A single mutating operation, applied server-side.
 */
export type ContentOp = { "op": "set", id: string, block: BlockPatch, } | { "op": "insert", anchor: Anchor, block: BlockInput, } | { "op": "delete", id: string, } | { "op": "move", id: string, anchor: Anchor, };
