// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * The body document: an ordered list of blocks. Stored as the project's
 * `detail_content` JSONB.
 */
export type ContentDoc = { blocks: Array<Block>, };
