// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All event types in the system, serialized as dot-separated strings
 */
export type EventType = "project.created" | "project.updated" | "project.deleted" | "project.tag_added" | "project.tag_removed" | "tag.created" | "tag.updated" | "tag.deleted" | "settings.updated" | "github.sync_completed" | "github.sync_failed" | "github.rate_limited" | "og.generated" | "og.failed" | "cache.invalidated";
