// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FocalPoint } from "./FocalPoint";

/**
 * Optional metadata stored with media
 */
export type MediaMetadata = {
  focalPoint?: FocalPoint;
  altText?: string;
  duration?: number;
};
