// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a session authenticates: an interactive browser cookie, or a long-lived
 * CLI bearer token.
 */
export type SessionType = "browser" | "cli";
