// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalLineKind } from "./TerminalLineKind";

export type TerminalLine = { t: TerminalLineKind, text: string, };
