// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a [`TerminalCast`], tagged by how it should be styled.
 */
export type TerminalLineKind = "cmd" | "out" | "err" | "muted";
